apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: emissary-ingress-
commonLabels:
  kind: emissary-ingress

bases:
  - ../../base

patchesStrategicMerge:
  - deployment.yaml
