apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: shared-charts-
commonLabels:
  kind: shared-charts

bases:
  - ../../base

patchesStrategicMerge:
  - resources/deployment.yaml
